### ISSUE TITLE
Probably a typo in Makefile.PL

### ISSUE THREAD

**Issue by twata1** [Leont/crypt-passphrase-scrypt#1]
Hello,

It appears to me that there is a typo on line 22 in Makefile.PL (Probably Crypt::Passphrase?).

Thank you,

**Comment by twata1** [comment]
It appears to me that there is also a typo on line 45 in Makefile.PL.

**Comment by Leont** [comment]
Indeed! Thanks for the report, I've just released a version with a fix.
